Repository exmaple/underScore, pull requests merged in 2020-06, with the labels that each got.

#26 Add Logging
  bot.py
  cogs/stats_commands.py
  the_mines/download/get_html.py
Labels: refactor

#34 Create tag-latest.yml
  .github/workflows/tag-latest.yml
Labels: documentation

#35 Fix latest tag
  .github/workflows/bump-version.yml
  .github/workflows/tag-latest.yml
Labels: documentation

#37 I27 blurb
  bot.py
  cogs/stats_commands.py
  requirements.txt
  the_mines/download/get_html.py
  the_mines/process/fussballdaten/process_blurb.py
  the_mines/process/fussballdaten/process_matchday.py
  utils/embedder.py
  utils/messages.py
  utils/misc.py
  utils/table_handler.py
Labels: enhancement

#38 Clean up command after call
  bot.py
  cogs/stats_commands.py
  utils/misc.py
Labels: enhancement

#43 Add testing
  .coveragerc
  .github/workflows/pythonappci.yml
  .gitignore
  pytest.ini
  test_requirements.txt
  tests/test_dummy_data.py
  tests/test_misc.py
  tests/test_process_blurb.py
  tests/test_process_matchday.py
  tests/test_table_handler.py
  the_mines/process/fussballdaten/process_blurb.py
Labels: testing

#44 i29 help page
  bot.py
  cogs/stats_commands.py
  utils/messages.py
Labels: enhancement
